### ISSUE TITLE
Question about DispersionCircle

### ISSUE THREAD

**Issue by tankista01** [StranikS-Scan/StranikS_Scan-mods#3]
Hi, 
I use your modification DispersionCircle, that show real dispersion circle, and I noticed, that some shots go out of the circle. Using your second mod SPGDispersion, to see coordinates of aim point, I measured a size of dispersion circle. What I have found it is smaller than 2*acc (gun accuracy). By changing scale of gui (in mod's setting pannel) I found that when scale is 1.4 the size of the circle look pretty good with my measuring with SPGDispersion.

What is more, in python file, is a line of code, where you divide original value of circle size by 2.3. Can you tell me, what 2.3 value mean? 

Oh, and I don't know if you are right person to whom I should write. I dont know if you, or spoter develop this mod now  ;)

**Comment by StranikS-Scan** [comment]
Hi! You can read about 2.3 in my [post](http://forum.worldoftanks.ru/index.php?/topic/1529130-%d0%b2%d1%81%d1%91-%d0%be-%d1%80%d0%b0%d0%b7%d0%b1%d1%80%d0%be%d1%81%d0%b5/page__st__200__pid__43149776#entry43149776). However, the information in the post may be a little out of date. The coefficient may also be outdated, since the developers made changes to the game interface.

**Comment by tankista01** [comment]
Thanks for fast replay. Unfortunately it's in russian, so there will be long night to read whole text :P
